#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Task App', '1.0');

try {
    $pdo = new PDO('mysql:host=127.0.0.1;dbname=command_line_tasks;', 'root', '');

    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (\PDOException $exception) {
    echo "Cannot Connect To The Database ";
    exit(1);
}

$dbAdapter = new Acme\DatabaseAdapter($pdo);

$app->add(new Acme\ShowCommand($dbAdapter));
$app->add(new Acme\AddCommand($dbAdapter));
$app->add(new Acme\CompleteCommand($dbAdapter));

$app->run();